# Permalinks
permalink:           pretty

# Setup
title:               Max Clarke
tagline:             How I Learned to Stop Worrying and Start Loving the Data
url:                 http://max-clarke.github.io
paginate:            2
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Max Clarke
  url:               https://twitter.com/
  email:             jmclarke51@gmail.com
# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/max-clarke

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist

# Page List
pages_list:       
  About: '/about'
  Archive: '/archive'
  Feed: '/index.html'
